name: Build MSI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install WiX Toolset (if needed)
        run: |
            choco install wixtoolset -y

      - name: Grant execution rights to Gradlew
        run: |
          git config --global core.autocrlf input
          chmod +x gradlew

      - name: Build MSI
        run: ./gradlew packageReleaseMsi --stacktrace

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-MSI
          path: composeApp/build/compose/binaries/main/msi/*.msi
